
name: myenv
channels:
  - defaults
dependencies:
  - python=3.8.10
  - pip
  - asttokens=2.4.1
  - attrs=19.3.0
  - Automat=0.8.0
  - backcall=0.2.0
  - blinker=1.4
  - certifi=2019.11.28
  - chardet=3.0.4
  - Click=7.0
  - cloud-init=23.3.3
  - colorama=0.4.3
  - comm=0.2.2
  - command-not-found=0.3
  - configobj=5.0.6
  - constantly=15.1.0
  - cryptography=2.8
  - cupshelpers=1.0
  - dbus-python=1.2.16
  - debugpy=1.8.5
  - decorator=5.1.1
  - defer=1.0.6
  - distro=1.4.0
  - distro-info=0.23+ubuntu1.1
  - entrypoints=0.3
  - executing=2.0.1
  - httplib2=0.14.0
  - hyperlink=19.0.0
  - idna=2.8
  - importlib_metadata=8.4.0
  - incremental=16.10.1
  - ipykernel=6.29.5
  - ipython=8.12.3
  - jedi=0.19.1
  - Jinja2=2.10.1
  - jsonpatch=1.22
  - jsonpointer=2.0
  - jsonschema=3.2.0
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - keyring=18.0.1
  - language-selector=0.1
  - launchpadlib=1.10.13
  - lazr.restfulclient=0.14.2
  - lazr.uri=1.0.3
  - line_profiler=4.1.3
  - macaroonbakery=1.3.1
  - MarkupSafe=1.1.0
  - matplotlib-inline=0.1.7
  - more-itertools=4.2.0
  - nest-asyncio=1.6.0
  - netifaces=0.10.4
  - nvidia-cublas-cu11=11.11.3.6
  - nvidia-cudnn-cu11=8.6.0.163
  - oauthlib=3.1.0
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - platformdirs=4.2.2
  - prompt_toolkit=3.0.47
  - protobuf=3.6.1
  - psutil=6.0.0
  - pure_eval=0.2.3
  - pyasn1=0.4.2
  - pyasn1-modules=0.2.1
  - pycairo=1.16.2
  - pycups=1.9.73
  - Pygments=2.18.0
  - PyGObject=3.36.0
  - PyHamcrest=1.9.0
  - PyJWT=1.7.1
  - pymacaroons=0.13.0
  - PyNaCl=1.3.0
  - pyOpenSSL=19.0.0
  - pyRFC3339=1.1
  - pyrsistent=0.15.5
  - pyserial=3.4
  - python-apt=2.0.1+ubuntu0.20.4.1
  - python-dateutil=2.9.0.post0
  - python-debian=0.1.36+ubuntu1.1
  - pytz=2019.3
  - PyYAML=5.3.1
  - pyzmq=26.2.0
  - requests=2.22.0
  - requests-unixsocket=0.2.0
  - screen-resolution-extra=0.0.0
  - SecretStorage=2.3.1
  - service-identity=18.1.0
  - simplejson=3.16.0
  - six=1.14.0
  - sos=4.5.6
  - ssh-import-id=5.10
  - stack-data=0.6.3
  - systemd-python=234
  - tornado=6.4.1
  - traitlets=5.14.3
  - Twisted=18.9.0
  - typing_extensions=4.12.2
  - ubuntu-advantage-tools=8001
  - ufw=0.36
  - unattended-upgrades=0.1
  - urllib3=1.25.8
  - wadllib=1.3.3
  - wcwidth=0.2.13
  - xkit=0.0.0
  - zipp=1.0.0
  - zope.interface=4.7.1
