
name: myenv
channels:
  - defaults
dependencies:
  - python=3.10.10
  - pip
  - absl-py=1.4.0
  - anyio=3.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - asttokens=2.2.1
  - astunparse=1.6.3
  - attrs=23.1.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - bleach=6.0.0
  - pip:
    - boltons @ file:///croot/boltons_1677628692245/work
  - brotlipy=0.7.0
  - cachetools=5.3.1
  - pip:
    - certifi @ file:///croot/certifi_1683875369620/work/certifi
  - pip:
    - cffi @ file:///croot/cffi_1670423208954/work
  - pip:
    - charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work
  - cloudpickle=2.2.1
  - comm=0.1.3
  - pip:
    - conda @ file:///croot/conda_1689210439356/work
  - pip:
    - conda-content-trust @ file:///tmp/abs_5952f1c8-355c-4855-ad2e-538535021ba5h26t22e5/croots/recipe/conda-content-trust_1658126371814/work
  - pip:
    - conda-package-handling @ file:///croot/conda-package-handling_1672865015732/work
  - pip:
    - conda_package_streaming @ file:///croot/conda-package-streaming_1670508151586/work
  - pip:
    - cryptography @ file:///croot/cryptography_1677533068310/work
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dm-sonnet=2.0.1
  - dm-tree=0.1.8
  - executing=1.2.0
  - fastjsonschema=2.16.3
  - flatbuffers=23.5.26
  - fqdn=1.5.1
  - future=0.18.3
  - gast=0.4.0
  - google-auth=2.22.0
  - google-auth-oauthlib=1.0.0
  - google-pasta=0.2.0
  - graph-nets=1.1.0
  - grpcio=1.56.0
  - h5py=3.9.0
  - pip:
    - idna @ file:///croot/idna_1666125576474/work
  - ipykernel=6.22.0
  - ipython=8.13.2
  - ipython-genutils=0.2.0
  - ipywidgets=8.0.6
  - isoduration=20.11.0
  - jedi=0.18.2
  - Jinja2=3.1.2
  - pip:
    - jsonpatch @ file:///tmp/build/80754af9/jsonpatch_1615747632069/work
  - jsonpointer=2.1
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter-console=6.6.3
  - jupyter-events=0.6.3
  - jupyter_client=8.2.0
  - jupyter_core=5.3.0
  - jupyter_server=2.5.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab-pygments=0.2.2
  - jupyterlab-widgets=3.0.7
  - keras=2.13.1
  - libclang=16.0.0
  - Markdown=3.4.3
  - MarkupSafe=2.1.2
  - matplotlib-inline=0.1.6
  - mistune=2.0.5
  - nbclassic=1.0.0
  - nbclient=0.7.4
  - nbconvert=7.3.1
  - nbformat=5.8.0
  - nest-asyncio=1.5.6
  - networkx=3.1
  - notebook=6.5.4
  - notebook_shim=0.2.3
  - numpy=1.24.3
  - oauthlib=3.2.2
  - opt-einsum=3.3.0
  - pip:
    - packaging @ file:///croot/packaging_1678965309396/work
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - platformdirs=3.5.0
  - pip:
    - pluggy @ file:///tmp/build/80754af9/pluggy_1648024709248/work
  - prometheus-client=0.16.0
  - prompt-toolkit=3.0.38
  - protobuf=4.23.4
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure-eval=0.2.2
  - pyasn1=0.5.0
  - pyasn1-modules=0.3.0
  - pip:
    - pycosat @ file:///croot/pycosat_1666805502580/work
  - pip:
    - pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
  - Pygments=2.15.1
  - pip:
    - pyOpenSSL @ file:///croot/pyopenssl_1677607685877/work
  - pyrsistent=0.19.3
  - pip:
    - PySocks @ file:///home/builder/ci_310/pysocks_1640793678128/work
  - python-dateutil=2.8.2
  - python-json-logger=2.0.7
  - PyYAML=6.0
  - pyzmq=25.0.2
  - qtconsole=5.4.2
  - QtPy=2.3.1
  - pip:
    - requests @ file:///croot/requests_1678709721434/work
  - requests-oauthlib=1.3.1
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rsa=4.9
  - pip:
    - ruamel.yaml @ file:///croot/ruamel.yaml_1666304550667/work
  - pip:
    - ruamel.yaml.clib @ file:///croot/ruamel.yaml.clib_1666302247304/work
  - Send2Trash=1.8.2
  - pip:
    - six @ file:///tmp/build/80754af9/six_1644875935023/work
  - sniffio=1.3.0
  - soupsieve=2.4.1
  - stack-data=0.6.2
  - tabulate=0.9.0
  - tensorboard=2.13.0
  - tensorboard-data-server=0.7.1
  - tensorflow=2.13.0
  - tensorflow-estimator=2.13.0
  - tensorflow-io-gcs-filesystem=0.32.0
  - tensorflow-probability=0.14.0
  - termcolor=2.3.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - pip:
    - toolz @ file:///croot/toolz_1667464077321/work
  - tornado=6.3.1
  - pip:
    - tqdm @ file:///croot/tqdm_1679561862951/work
  - traitlets=5.9.0
  - typing_extensions=4.5.0
  - uri-template=1.2.0
  - pip:
    - urllib3 @ file:///croot/urllib3_1680254681959/work
  - wcwidth=0.2.6
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.5.1
  - Werkzeug=2.3.6
  - widgetsnbextension=4.0.7
  - wrapt=1.15.0
  - pip:
    - zstandard @ file:///croot/zstandard_1677013143055/work
