name: /home/s3378209/data1/envs/gnets2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - comm=0.2.2
  - debugpy=1.8.2
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - importlib-metadata=8.0.0
  - importlib_metadata=8.0.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libedit=3.1.20191231
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=14.1.0
  - libgomp=14.1.0
  - libnsl=2.0.1
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libstdcxx-ng=14.1.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.3.1
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - psutil=6.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.18.0
  - python=3.11.9
  - python-dateutil=2.9.0
  - python_abi=3.11
  - pyzmq=26.0.3
  - readline=8.2
  - setuptools=70.1.1
  - six=1.16.0
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.19.2
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - autoray==0.6.12
      - cachetools==5.3.3
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - contourpy==1.2.1
      - cotengra==0.6.2
      - cycler==0.12.1
      - cython==3.0.10
      - cytoolz==0.12.3
      - dm-sonnet==2.0.2
      - dm-tree==0.1.8
      - etils==1.12.2
      - flatbuffers==24.3.25
      - fonttools==4.53.1
      - fsspec==2025.3.0
      - future==1.0.0
      - gast==0.6.0
      - google-auth==2.32.0
      - google-auth-oauthlib==1.2.1
      - google-pasta==0.2.0
      - graph-nets==1.1.0
      - grpcio==1.64.1
      - gviz-api==1.10.0
      - h5py==3.11.0
      - idna==3.7
      - importlib-resources==6.5.2
      - kahypar==1.3.5
      - keras==2.15.0
      - kiwisolver==1.4.5
      - libclang==18.1.1
      - line-profiler==4.1.3
      - llvmlite==0.43.0
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - mdurl==0.1.2
      - memory-profiler==0.61.0
      - ml-dtypes==0.3.2
      - namex==0.0.8
      - networkx==3.3
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.2.5.6
      - nvidia-cuda-cupti-cu12==12.2.142
      - nvidia-cuda-nvcc-cu12==12.2.140
      - nvidia-cuda-nvrtc-cu12==12.2.140
      - nvidia-cuda-runtime-cu12==12.2.140
      - nvidia-cudnn-cu12==8.9.4.25
      - nvidia-cufft-cu12==11.0.8.103
      - nvidia-curand-cu12==10.3.3.141
      - nvidia-cusolver-cu12==11.5.2.141
      - nvidia-cusparse-cu12==12.1.2.141
      - nvidia-nccl-cu12==2.16.5
      - nvidia-nvjitlink-cu12==12.2.140
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - optree==0.12.1
      - pandas==2.2.2
      - pillow==10.4.0
      - pip==24.1.2
      - plotext==5.3.2
      - protobuf==4.25.3
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pyparsing==3.1.2
      - pytz==2024.1
      - quimb==1.8.0
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rich==13.7.1
      - rsa==4.9
      - scipy==1.13.0
      - seaborn==0.13.2
      - tabulate==0.9.0
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-profile==2.19.0
      - tensorflow==2.15.1
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.4.0
      - toolz==0.12.1
      - tqdm==4.66.4
      - tzdata==2024.1
      - urllib3==2.2.2
      - werkzeug==3.0.3
      - wrapt==1.14.1
